package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/emilhauk/msg/internal/middleware"
	redisclient "github.com/emilhauk/msg/internal/redis"
	"github.com/emilhauk/msg/internal/storage"
)

const maxUploadBytes = 50 << 20 // 50 MiB

// allowedContentTypes lists the MIME types accepted for media uploads.
var allowedContentTypes = map[string]bool{
	"image/jpeg": true,
	"image/png":  true,
	"image/gif":  true,
	"image/webp": true,
	"video/mp4":  true,
	"video/webm": true,
}

// UploadHandler handles presigned URL generation for direct-to-S3 uploads.
type UploadHandler struct {
	Redis *redisclient.Client
	S3    *storage.S3Client
}

type presignResponse struct {
	UploadURL string `json:"upload_url"`
	PublicURL string `json:"public_url"`
	Key       string `json:"key"`
}

// HandlePresignURL handles GET /rooms/{id}/upload-url.
//
// Query parameters:
//
//	hash           — 12-char random hex string generated by the client (used as the filename stem)
//	content_type   — MIME type of the file to be uploaded
//	content_length — byte size of the file
//
// Returns 200 with JSON { upload_url, public_url, key }.
func (h *UploadHandler) HandlePresignURL(w http.ResponseWriter, r *http.Request) {
	roomID := r.PathValue("id")
	user := middleware.UserFromContext(r.Context())

	ok, err := h.Redis.IsRoomAccessible(r.Context(), roomID, user.ID)
	if err != nil || !ok {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	q := r.URL.Query()
	hash := q.Get("hash")
	contentType := q.Get("content_type")
	contentLengthStr := q.Get("content_length")

	if hash == "" || contentType == "" || contentLengthStr == "" {
		http.Error(w, "hash, content_type and content_length are required", http.StatusBadRequest)
		return
	}

	if !allowedContentTypes[contentType] {
		http.Error(w, "unsupported content type", http.StatusBadRequest)
		return
	}

	contentLength, err := strconv.ParseInt(contentLengthStr, 10, 64)
	if err != nil || contentLength <= 0 {
		http.Error(w, "invalid content_length", http.StatusBadRequest)
		return
	}
	if contentLength > maxUploadBytes {
		http.Error(w, fmt.Sprintf("file exceeds maximum allowed size of %d MiB", maxUploadBytes>>20), http.StatusRequestEntityTooLarge)
		return
	}

	// Derive the file extension from the validated content type (server-controlled).
	ext := storage.ExtForContentType(contentType)
	name := hash + "." + ext

	// Build a unique key prefix using timestamp + user ID (mirrors message ID format).
	msgPrefix := fmt.Sprintf("%d-%s", time.Now().UnixMilli(), user.ID)
	key := storage.MediaKey(roomID, msgPrefix, name)

	uploadURL, err := h.S3.PresignPut(r.Context(), key, contentType, contentLength)
	if err != nil {
		http.Error(w, "failed to generate upload URL", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(presignResponse{
		UploadURL: uploadURL,
		PublicURL: h.S3.PublicURL(key),
		Key:       key,
	})
}
